# Generated by Django 2.1.5 on 2019-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientexpenses', '0003_auto_20190109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
