# Generated by Django 2.1.5 on 2019-01-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientexpenses', '0004_auto_20190109_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_expense', to='clientexpenses.Client'),
        ),
    ]
